- id: 'tf_init_apply'
  name: 'devopsevd/gcloudterraform:1.0'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      echo "************Print Current Directory************"
      pwd
      echo "************Listing Files************"
      ls -la
      echo "************Terraform Init************"
      terraform init
      echo "************Terraform Plan************"
      terraform plan
      echo "************Terraform Apply************"
      terraform apply -auto-approve
options:
  logging: CLOUD_LOGGING_ONLY
