steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'terraform init'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'terraform plan -out=tfplan'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'terraform apply -auto-approve tfplan'

options:
  logging:
    # Specify a Cloud Storage bucket for build logs
    path: 'gs://buildlogs-1231'
